refraction-networking/utls

u_common.go, u_conn.go, u_parrots.go
With last refactoring, that enabled flexible external configs(and ultimately enabled effortless use of auto-generated code for any fingerprint, including recently integrated [iOS 11](https://tlsfingerprint.io/id/a9ecd7afe6b0e4a4) one), we introduced a regression:
*Various connections, using same ClientHelloSpec may share state.*
To provide more info on what state was erroneously shared, here are some examples:
- Shared slice with curves for `SupportedCurvesExtension` - should only change, if manually changed by user, which I don't think anyone does.
- List of ALPN values in extensions might be realistically be changed by user(albeit, it shouldn't be! danger! Chrome-like fingerprint without `h2` looks weird and sticks out!). Such change would persist for all subsequent usages of same …
=> Fix statefulness

examples/examples.go, u_conn.go, u_parrots.go
As @AxbB36 reported, there were 2 types of issues with randomized parrot when tested against golang.org and ajax.aspnetcdn.com
1. Some servers would get upset if TLS 1.3 is being negotiated, but PSS signature algorithms are absent. Spec https://tools.ietf.org/html/rfc8446 seems to only briefly mention that it's mandatory in some way
```
-  Implementations that advertise support for RSASSA-PSS (which is
mandatory in TLS 1.3) MUST be prepared to accept a signature using
that scheme even when TLS 1.2 is negotiated.  In TLS 1.2,
RSASSA-PSS is used with RSA cipher suites.
```
2. `crypto/tls` doesn't actually support multiple key shares and may only keep track of one, so we should just send one
=>  Fixes intermittent issues with Randomized parrot

u_common.go, u_parrots.go, u_prng.go, u_roller.go
- Address seed size and PRNG stream size issues discussed in
https://github.com/refraction-networking/utls/pull/20 using a
pared down version of
github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon/common/prng,
a chacha20-based CSPRNG; includes license change
- Add explicit Seed field to ClientHelloID; seed field and functions
exported to support external initialization
- Replace custom random helpers with standard library implementations
=> Replace PRNG

u_parrots.go
Copy slice returned by defaultCipherSuitesTLS13 before modifying to prevent data race against underlying varDefaultCipherSuitesTLS13 global variable.
This change simply copies the treatment given to `p.CipherSuites`: https://github.com/refraction-networking/utls/blob/7c97cdb47655017af7126d6c5cd23ace4469d7aa/u_parrots.go#L506-L507
Data race detected with concurrent UConn-based dials:
```
WARNING: DATA RACE
Write at 0x00c0000c808a by goroutine 127:
.../github.com/refraction-networking/utls.(*UConn).generateRandomizedSpec.func1()
.../github.com/refraction-networking/utls/u_parrots.go:518 +0x134
math/rand.(*Rand).Shuffle()
/usr/local/go/src/math/rand/rand.go:253 +0xc4
.../github.com/refraction-networking/utls.(*UConn).generateRandomizedSpec() …
```
=> Fix data race

u_parrots.go
Currently, SessionCache is not used for non-HelloGolang fingerprints,
and this PR is what the fix would potentially look like.
This is only for the TLS 1.2, support for TLS 1.3 PSK resumption cache remains a TODO.
Supposedly fixes #27, not tested yet
@rod-hynes
=> WIP: fix TLS 1.2 session cache

README.md, u_common.go, u_conn.go, u_parrots.go, u_tls_extensions.go
I am a bit too lazy to split those features, as they are tied together in the code.
* Adds fingerprints for Chrome 75, iOS 12.1, and Firefox 65(=Firefox 63)
* If min/max tls versions are not explicitly specified in the ClientHelloSpec,
uTLS will try to parse versions from SupportedVersions extension,
and fallback to [TLS 1.0, TLS 1.2] if SupportedVersions is absent.
* Adds mimicked FakeRecordSizeLimitExtension and FakeCertCompressionAlgsExtension
to be used instead of GenericExtension{} for clarity and extensibility
(we are ready to use those with Firefox and Chrome fps with correct values
whenever actual functionality is implemented)
=> Update fingerprints + add default spec version

u_conn.go, u_parrots.go, u_public.go
In order to avoid panics, we make sure that no pointer is dereferenced
during transformation between public and private handshake state.
Presumably fixes #29
=> Fix panic in u_public by never dereferencing

u_parrots.go, u_tls_extensions.go
Renegotiation:
- Disallow specifying the body of Renegotiation extensions to
avoid assumption that it will be verified.
- Marshal the extension, if it is present in the uconn.Extensions list,
even if Renegotiation is set to Never.
Exports all unexported uTLS extension fields.
Fixes #33
=> Fix #33: renegotiation and export extension fields

u_common.go, u_parrots.go
New Chrome 83 fingerprint.
Removed:
* 3DES cipher suite (https://tlsfingerprint.io/find/cipher/000a)
* sha1 signature algorithm (rsa_pkcs1_sha1 (0x0201))
=> Add Chrome 83 fingerprint

u_conn_test.go
I've been trying to run the `-update` tests in order to fix the testdata for https://github.com/refraction-networking/utls/pull/38 and ran into a couple issues that I hope this PR addresses.
The first is that it seems as though the openssl command as populated currently ends up as:
```
openssl s_server -no_ticket -num_tickets 0 openssl s_server -cipher TLS_AES_128_GCM_SHA256 -tls1_3 -cert /tmp/go-tls-test334278555 -certform DER -key /tmp/go-tls-test012468798 -accept 24323
```
where `openssl` is repeated. It looks to me like the `openssl s_server` is already defined in https://github.com/refraction-networking/utls/blob/master/handshake_client_test.go#L170 so we can remove the `"openssl", "s_server"` values from the `args` slice.
The other is changing the `-cipher` flag to `-ciphersuites` …
=> Fix openssl command arguments for update tests

README.md
I see a lot of people asking to add support for a specific extensions (for example, #113, #108, #107). However, the need is often to match required TLS ClientHello fingerprint and not to actually implement functionality required by such extensions. uTLS already has `Fake*` extensions which only serve as a placeholders, and `GenericExtension`, which (as stated in comments) "allows to include in ClientHello arbitrary unsupported extensions".
Thus I'd like to contribute documentation on creating such extensions.
=> Document adding custom fake TLS extensions

common.go, u_common.go, u_parrots.go, u_prng.go, u_tls_extensions.go
Various ClientHellos and TLS extensions are included in this PR, from [Psiphon-Labs](https://github.com/Psiphon-Labs/utls) , [Noooste](https://github.com/Noooste/utls/), and [sleeyax](https://github.com/sleeyax/utls).
Fingerprints and extensions were tested by comparing Wireshark captures from our ClientHellos to captures from real browsers (and the extensions being used). 
[Psiphon-Labs](https://github.com/Psiphon-Labs/utls) :
- HelloChrome102 (tested) 
- HelloFirefox102 (tested)
- change to HelloRandomized to include ApplicationSettingsExtension 
[sleeyax](https://github.com/sleeyax/utls):
- Chrome_87
- Chrome_96
- iOS_13 (tested)
- iOS14 (tested)
- Android11
- ApplicationSettingsExtension
[Noooste](https://github.com/Noooste/utls/):
- Firefox99 (tested)
- Chrome100 
- …
=> new ClientHellos and Extensions 

common.go, u_common.go, u_fingerprinter.go, u_parrots.go, u_tls_extensions.go
Also add faked support for token binding, ALPS, and delegated credentials.
This add new `ClientHelloSpec` based on:
- Firefox 105
- Chrome 106
- Edge 106
- Safari 16.0
- 360 Secure Browser 11.0
- QQ Browser 11.1
Unfortunately, the specs based on Edge 106 and 360 11.0 seem to incompatible with this library.  I haven't had time yet to investigate why.  I added the specs anyway in case they are useful to some people.  Perhaps they will function in limited use cases.  I did not update `HelloEdge_Auto` and `Hello360_Auto` to avoid breaking code dependent on those references.
=> Add new ClientHellos

u_parrots.go
Implements #135: exporting `utlsIdToSpec()` function as `UTLSIdToSpec()` per request.
=> Exports `utlsIdToSpec()` as `UTLSIdToSpec()`

u_public.go
Allow parsed or generated `PubClientHelloMsg` to be marshaled back to bytes.
=> Marshal Public ClientHello

u_common.go, u_parrots.go
Fixes #132. 
- added `HelloChrome_107` (commented as beta and not used by `HelloChrome_Auto`)
- added `shuffleExtensions()` to shuffle the order of extensions in a `ClientHelloSpec`
=> feat: Chrome 106 Shuffled Fingerprint

common.go, conn.go, handshake_client_tls13.go, handshake_messages.go, handshake_messages_test.go, key_agreement.go, tls_test.go, u_common.go, u_conn.go, u_fingerprinter.go, u_handshake_client.go, u_handshake_messages.go, u_tls_extensions.go
Implemented support for `ApplicationSettingsExtension` -- now the handshake message could be recognized! 
PR based on #141. Fixes #124 and #140.
Credits: Major implementation work is done by @blakebyrnes in `ulixee/utls`.
=> feat: Implement ALPS extension

handshake_client.go, u_tls_extensions.go
Currently it is not possible for UTLS clients to connect to OpenSSL servers (and probably any RFC compliant server) when performing mutual TLS authentication and using the extended master secret extension (and using TLSv1.2)
The session hash used in extended master secret does not include the CertificateVerify handshake message. see: https://www.rfc-editor.org/rfc/rfc7627#section-3
```
When a full TLS handshake takes place, we define
session_hash = Hash(handshake_messages)
where "handshake_messages" refers to all handshake messages sent or
received, starting at the ClientHello up to and including the
ClientKeyExchange message, including the type and length fields of
the handshake messages.  This is the concatenation of all the
exchanged Handshake structures, as defined in Section 7.4 of …
```
=> Fix Client Certificate Verification when Using Extended Master Secret

u_parrots.go
`UTLSIdToSpec` allows user to get `ClientHelloSpec` for all fixed fingerprints, but randomized `ClientHelloSpec` cannot be generated that way - all randomization happens inside `UConn`'s private methods. As a library user, I'd like to have a way to get randomized clientHello directly, without having to create `UConn`.
This pull requests adds such functionality.
=> Add randomized clientHello generation in UTLSIdToSpec.

u_parrots.go
=> Support randomized with non-nil seed in UTLSIdToSpec

u_common.go
Use the shuffled Chrome fp `HelloChrome_106_Shuffle` which mimics the latest Chrome's behavior including shuffling the extensions per each `ClientHello` message.
See https://tlsfingerprint.io/norm_fp for more information.
=> Bump HelloChrome_Auto version

conn.go
https://github.com/golang/go/pull/58912
=> crypto/tls: reject change_cipher_spec record after handshake in TLS 1.3

common.go
https://github.com/golang/go/pull/58913
=> crypto/tls: set const maxUselessRecords to 32 (the same with OpenSSL)

common.go, handshake_messages.go, internal/helper/typeconv.go, u_common.go, u_conn.go, u_fingerprinter.go, u_fingerprinter_test.go, u_parrots.go, u_public.go, u_tls_extensions.go
Partially implements #164.
----
Integrated commits/changes from #148 to prevent merge conflict on #148. Merging this PR should close #148.
=> feat: Convert raw bytes or tlsfingerprint record to ClientHelloSpec

common.go, handshake_client.go, tls_test.go
(empty)
----
_Summary added by @gaukas:_
- Added a flag `InsecureSkipTimeVerify` in `Config` to allow skipping client's validation on the `NotAfter` field of server returned certificates against current time. 
- Patched `(*Conn).loadSession()` to also support `config.InsecureServerNameToVerify`, a flag added in a previous commit.
=> Add `InsecureSkipTimeVerify`

conn.go
Implication is ALPS peer settings are never copied to the connection state.
=> fix: connection state locked never called

u_common.go, u_parrots.go, u_tls_extensions.go
- Shuffle Function will no longer shuffle PSK.
- Shuffle Function optimized.
- Fixed a bug in `FakePresharedKeyExtension` causing program to panic.
- Added `HelloChrome_100_PSK` and `HelloChrome_112_PSK_Shuf`. Both are beta fingerprints, use at your own risk.
=> fix: don't shuf psk

u_conn.go
Fixes #191 by allowing `SupportedVersions` extension to support ONLY TLS 1.3 by include no other versions (and therefore enforce TLS 1.3 being negotiated and break 1.2-only servers).
=> fix: allow TLS 1.3 as min TLS version

u_parrots.go
Removed a legacy assignment to `hello.CipherSuites` in `ApplyPreset()` which gets overwritten later in code. 
Closes #183. 
Thanks @4cq2!
=> fix: removed redundant assignment

.github/workflows/go_1_19.yml, .github/workflows/go_1_20.yml, .github/workflows/go_1_21_rc3.yml
- old stable: Go 1.19
- stable: Go 1.20
- beta: Go 1.21rc3
Note that currently we expect tests to fail on Go 1.20 and Go 1.21rc3. Once Go 1.21 becomes stable we will drop Go 1.19
Closes #202.
=> workflow: add more version build/test actions

boring.go, boring_test.go, conn.go, handshake_client.go, handshake_client_test.go, handshake_client_tls13.go, handshake_messages.go, handshake_server.go, quic.go, tls_test.go
=> sync: [release-branch.go1.21] crypto/tls: restrict RSA keys in certificates to <= 8192 bits

u_parrots.go
A hotfix for a nil pointer dereference error.
=> fix: don't deref nil ptr

u_quic_transport_parameters.go, u_quic_transport_parameters_test.go
- Rename GREASE to GREASETransportParameter.
- Rename Padding to PaddingTransportParameter.
- Adding GREASE QTP ID check against `id >= 27`. Otherwise `max_ack_delay = 11` will be incorrectly recognized as a GREASE value.
Fix #213.
=> fix: poorly named qtps

handshake_client.go
This is a fix that patches one of the file from upstream (`crypto/tls`), by skipping saving to ClientSessionCache when it is not set in the Config, it allows TLS 1.2 connections to be established while client actively advertises `session_ticket` extension, without modifying configs from previous tagged versions. 
Closes #218.
=> fix: skip saving to c.config.ClientSessionCache if it is nil

u_common.go, u_conn.go, u_parrots.go
* new: PQ and other parrots
Add new preset parrots:
- HelloChrome_114_Padding_PSK_Shuf
- HelloChrome_115_PQ
- HelloChrome_115_PQ_PSK
* new: ShuffleChromeTLSExtensions
Implement a new function `ShuffleChromeTLSExtensions(exts []TLSExtension) []TLSExtension`.
* update: include psk parameter for parrot-related functions
Update following functions' prototype to accept an optional pskExtension (of type *FakePreSharedKeyExtension):
- `UClient(conn net.Conn, config *Config, clientHelloID ClientHelloID)` => `UClient(conn net.Conn, config *Config, clientHelloID ClientHelloID, pskExtension ...*FakePreSharedKeyExtension)`
- `UTLSIdToSpec(id ClientHelloID)` => `UTLSIdToSpec(id ClientHelloID, pskExtension ...*FakePreSharedKeyExtension)`
* new: pre-defined error from UTLSIdToSpec
Update …
=> new: more parrots and safety update

auth.go, auth_test.go, cfkem.go, cfkem_test.go, common.go, generate_cert.go, go.mod, go.sum, handshake_client.go, handshake_client_tls13.go, handshake_server.go, handshake_server_tls13.go, key_agreement.go, prf.go, tls.go, tls_cf.go, tls_test.go, u_common.go, u_conn.go, u_handshake_client.go, u_parrots.go, u_public.go
~~_Work in Progress..._~~
Done! We can get `_PQ` parrots now. 
- We skipped/modified a few test cases in order to prevent merging breaking changes made by cloudflare which requires heavy modification or rebuilding Go.
=> uTLS: X25519Kyber768Draft00 hybrid post-quantum key agreement

examples/tls-resumption/main.go
Probably we should check that state is nil rather than the map?
=> Fix removing session state

u_conn.go
Fix an unchecked overriding behavior which may lose pre-created handshake keys.
Fix #237.
=> fix: secondary keyshares may be lost after overriding `keySharesParams`

u_pre_shared_key.go
=> Deprecate usage of `OmitEmptyPsk` field in `PreSharedKeyExtension` (closes #255)

u_common.go, u_tls_extensions.go
* Add a function `AlwaysPadToLen` to generate padding styles according to the raw clienthello. 
* Add an extra step in `FromRaw` after parsing the extension list to update the padding style.
Fix #262.
=> fix: no padding if raw clienthello is too short

u_common.go, u_parrots.go
Since Chrome hasn't started enabling `TLS 1.3 hybridized Kyber support` by default, It's necessary to have an non-PQ ClientHello support in my opinion.
=> feat: chrome 120 non-pq client hello

u_ech.go, u_parrots.go
=> fix: grease ech parrot for chrome 120

u_parrots.go
Based on discussion in #270 and observations, Firefox (NSS) GREASE ECH parrot was configured with incorrect parameters and needs a fix similar to #271.
=> fix: incorrect firefox nss parrot ECH params

u_parrots.go
`math/rand` might not be randomly seeded as documented on some platforms, including WebAssembly (when compiled with TinyGo v0.30.0).
=> security: crypto/rand ShuffleChromeTLSExtensions

u_conn.go, u_tls_extensions.go
Close #291: `(*UConn).Read()` incorrectly calling `(*Conn).Handshake()`
Close #284: Secure Renegotiation fails due to #291 and RenegotiationExt was Fake.
=> fix: `(*UConn).Read()` and Secure Renegotiation

u_parrots.go
Fixes two missing extension from the HelloFirefox_120 parrot:
* An empty `session_ticket (35)`
* `psk_key_exchange_modes (45)` with `psk_dhe_ke` mode.
This is tested with Firefox 120 and Firefox 123.
=> Update Firefox 120 parrot to a more popular version

u_parrots.go
by RFC 9000 Section 8.4, QUIC must not send non-empty (legacy) session ID, otherwise server will return error.
* It is also weird that so far we see no error from server due to uquic sending 32-byte session ID.
=> quic: always use empty session ID

handshake_client.go
This PR fixes an issue where server cert expiry is verified even though `Config.InsecureSkipTimeVerify` is set to true.
It seems that this issue has come about after the uTLS sync with Go 1.21, where the upstream crypto/tls has moved the code to verify server cert expiry above the InsecureSkipVerify check.
=> Fix Config.InsecureSkipTimeVerify not being respected

u_conn.go, u_public.go
-  Fixes a bug introduced in https://github.com/refraction-networking/utls/pull/301 where `(*sessionController).shouldLoadSession` always returns `shouldReturn`.
- Adds additional setters for ClientSessionState to set fields required to generate an out-of-band PSK.
Review by the uTLS maintainers is much appreciated.
=> Fixes session ticket / PSK not set

u_handshake_client.go
Fixes an issue where `clientHelloMsg.extendedMasterSecret`/`PubClientHelloMsg.Ems` is always true, even if the extended_master_secret extension is not set in the Client Hello (e.g. from a random TLS profile).
=> fix: extMasterSecret mismatch with extended_master_secret extension

u_common.go, u_parrots.go
ML-KEM is now part of Chrome 131 as foreshadowed here:
https://security.googleblog.com/2024/09/a-new-path-for-kyber-on-web.html
I added it as `HelloChrome_131` instead of `HelloChrome_131_PQ` because post quantum is enabled by default but I'm open to changes.
=> Add Chrome 131 parrot and ML-KEM support

ech.go, handshake_client.go, handshake_client_tls13.go, handshake_messages.go, handshake_test.go, tls_test.go, u_conn.go, u_conn_test.go, u_handshake_client.go
This PR enables ECH when the user provides a ClientHello spec that has an extension implementing the `EncryptedClientHelloExtension` interface (such as the `GREASEEncryptedClientHelloExtension` currently for all the browsers) and follows the standard library’s ECH API of providing the `EncryptedClientHelloConfigList` in the config. 
When ECH is enabled, we generate another ClientHello as the ClientHelloInner using the standard library’s handshake marshaling functions and encode it in our ClientHelloOuter. Some extensions are substituted in the OuterExtensions list, in which case the uTLS generated values in the ClientHelloOuter will be used. We reorder the OuterExtensions list according to the structure in the outer ClientHello spec.
=> feat: add support for ECH when using custom clienthello specs

handshake_test.go, u_conn_test.go, u_handshake_client.go, u_public.go
Add TLS downgrade protection code from stdlib to `uconn.clientHandshake`. Also fix a related nil pointer dereference bug. 
Closes #181
=> Fix check for TLS downgrade canary

u_conn.go, u_parrots.go, u_tls_extensions.go
Update ECH outer SNI during ApplyPreset instead of Marshal so that it is not copied multiple times. Do not override server name in config when ECH is enabled.
Fixes #340
=> fix: prevent copying outer server name in inner

dicttls/exttype_values.go, u_common.go, u_conn.go, u_handshake_client.go, u_handshake_messages.go, u_parrots.go, u_tls_extensions.go
Since Chrome 133 the TLS fingerprint is changing due to this feature:
https://chromestatus.com/feature/5149147365900288
I found that others are also running into this problem here: https://github.com/refraction-networking/utls/issues/330
It looks like a "full" implementation might be bigger than just extending the current application settings extension, as per another implementation here:
https://github.com/bogdanfinn/utls/commit/fe91add3ecedd324b1b3b395c7b8bc0f72f224da
Opening this PR as a draft to discuss how we should move forward on this, I've also implemented [this](https://github.com/refraction-networking/utls/issues/330#issuecomment-2743313690) for the time being as it might be enough to address this (at least for my use case)
=> Implement Chrome 133+ support

u_handshake_client.go
For https://github.com/XTLS/REALITY/commit/69793c864044ae04455c3e4aac9925c0650d990, I need to visit `serverHello` in VerifyPeerCertificate()
=> Expose `serverHello` earlier in clientHandshake()
